---
- hosts: localhost

  tasks:
    #- name: test
      #batfish_firewall:
      #  network_name: network-example-filters
      #  snapshot_name: mycurrent
      #  snapshot_path: snapshot
      #  src: 10.20.0.0
      #  dest: 2.2.2.2
      #  acl_name: SPLIT-ACL
      #  node: 'ciscoasa'
      #  condition: permit
      #register: result

    - import_role:
        name: batfish_testfilter


